server:
  port: 8081
spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/outs?serverTimezone=GMT%2B8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  mapper-locations: classpath:mappers/*.xml
logging:
  level:
    cn:
      soft: DEBUG